# Generated by Django 4.1.1 on 2022-10-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_favbooks_name_favbooks_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favbooks',
            old_name='title',
            new_name='btitle',
        ),
        migrations.RemoveField(
            model_name='favbooks',
            name='description',
        ),
    ]
