# Generated by Django 4.1.1 on 2022-10-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_title_favbooks_btitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favbooks',
            name='user',
            field=models.CharField(default='ignore', max_length=100),
            preserve_default=False,
        ),
    ]
